exports.lrc_notfound = '抱歉, 没找到歌词';
exports.account_missing = '请先设置豆瓣账户再操作: $ douban.fm config';
exports.setup_fail = '啊哦，启动出错了，请检查配置文件 ~/.douban.fm.profile.json';
exports.love_fail = '未知曲目无法加心';
exports.normal = '出错了, 请稍后再试...';
exports.last_song = '这是最后一首了哦，回车以加载最新列表';
exports.turn_to_local_mode = '获取豆瓣电台频道出错，切换为本地电台...';
exports.mkdir_fail = '创建歌曲文件夹出错，请检查权限';
exports.localsongs_notfound = '没有找到本地音乐';